/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rapture_NeoscryptWrapper */

#ifndef _Included_com_rapture_NeoscryptWrapper
#define _Included_com_rapture_NeoscryptWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rapture_NeoscryptWrapper
 * Method:    neoscrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_rapture_NeoscryptWrapper_neoscrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
